### ISSUE TITLE
log out component doesn't trigger a successful log out?

### ISSUE THREAD

**Issue by iainkirkpatrick** [root-systems/dogstack-agents#13]
i can investigate :)

for now, simply enter `localStorage.clear()` in the console to log out

**Comment by ahdinosaur** [comment]
oops, we forgot to change the corresponding code here from https://github.com/root-systems/cobuy/pull/183. namely https://github.com/root-systems/dogstack-agents/blob/master/authentication/components/LogOut.js to match the new props signature being passed in.

**Comment by danalexilewis** [comment]
@ahdinosaur would having propTypes have caught this?

**Comment by ahdinosaur** [comment]
@agentlewis it's not that i wasn't aware, it's that i forgot to do it before merging the other code.

**Comment by ahdinosaur** [comment]
this is fixed with #17
